name: Build Lantern Library

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: zulu

      - name: Build (assembleRelease)
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :lantern-android:assembleRelease
